Customer orders feature
kabisa/headless-commerce-poc pull request #11
Opened 2021-06-17 13:47 UTC by alianza

Customer orders feature

Logged in customers can observe their past orders and their attributes like number, status and purchased items
Added feedback to user when loggin in and out
10 past orders are initially loaded
10 new orders are loaded when scrolled to the bottom of the page
Added logged out view to profile page
Added jest and cypress tests

2021-06-21 14:07 UTC, egonm12 requested changes

2021-06-21 14:07 UTC, egonm12 commented on pages/orders.tsx
> +  }, [atBottom])
This is an example of why you should put the eslint rule for hook dependency to 'error'. The dependency list is not correct. 
This hooks reads as "every time `atBottom` changes run this effect. While it should actually be: 'every time the `orders` or `data.orders.pageInfo.hasNextPage` changes run this effect.
`atBottom` is not a dependency of this effect.
If you don't fully understand the working of the dependency list of hooks we can call if you want.

2021-06-21 14:07 UTC, egonm12 commented on pages/orders.tsx
> +    window.addEventListener('scroll', () => {
Can you implement some throttle or debounce for this? Now it runs on every scroll.

Next to that, please move the anonymous function inside a variable and make sure to run the `useEffect` clean up function so we prevent memory leaks. Check https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1 for more info and an example.

2021-06-21 14:07 UTC, egonm12 commented on tests/customerAccessTokenCreate.ts
> +  const tokenResponse = await doFetch('post', tokenBody);
Even though it is a test file try to add types to these values so that casting is not needed on line 17

2021-06-21 14:07 UTC, egonm12 commented on tests/doFetch.ts
> +    method: method,
Not something you need to change but in js you can use a shorthand here:
```suggestion
    method,
```

2021-06-21 14:07 UTC, egonm12 commented on tests/orders.test.ts
> +  // console.log(orders);
Please remove the commented code from line 35 till 39

2021-06-21 14:07 UTC, egonm12 commented on tests/products.test.ts
> +  // // console.log(products);
Here as well

2021-06-22 09:31 UTC, alianza commented on cypress/integration/tests/orders.spec.js
> +    cy.wait(250)
I added the cypress-wait-until package for waiting for specific elements. This 250ms wait is still required for some reason otherwise the 'Accept cookies' button will become detached from the DOM in-between querying for it and clicking on it for some reason.

2021-06-22 09:55 UTC, alianza commented on pages/orders.tsx
> +  }, [atBottom])
Aha okay I get it now. I have fixed the dependencies and removed the loadnext function. It is all done in the hooks now.

2021-06-22 10:21 UTC, alianza commented on pages/orders.tsx
> +    window.addEventListener('scroll', () => {
I added a throttle at 500ms on the scroll listener and moved it out of the anonymous function to be cleaned up after.

2021-06-22 10:33 UTC, alianza commented on tests/doFetch.ts
> +    method: method,
Very useful to know! I will leave it like this for now for readability though.

2021-06-22 11:45 UTC, alianza commented
I think this is ready to merge! I have implemented all feedback from Egon successfully and fixed the merge conflicts.

2021-06-22 11:51 UTC, egonm12 approved these changes

2021-06-22 12:24 UTC, merged

2021-06-23 11:54 UTC, pascalw commented
@alianza @egonm12 I only noticed this now, but I see this is using the actual Shopify backend with some hardcoded credentials. In a real project we wouldn't do this, but instead we would mock out the external dependency (Shopify), to keep the test suite fast, isolated from external factors and to make sure we can easily control the external dependency (for example simulate a Shopify API error).

For the purpose of this project this is perhaps not a big deal, though I would like you @alianza to learn how things are done in real projects. I'll add a story to the backlog for the next sprint to implement a Shopify mock for the purpose of testing.