Personalisation
kabisa/headless-commerce-poc pull request #23
Opened 2021-06-29 15:29 UTC by alianza

Personalisation!

On homepage added recommended product to the list of products based on random product from brands of past 3 orders of logged in user.

2021-06-30 14:04 UTC, alianza commented
⚡️ [Lighthouse report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1625061842070-62728.report.html) for the changes in this PR:
| Category | Score |
| --- | --- |
| 🔴 Performance | 38 |
| 🟢 Accessibility | 100 |
| 🟢 Best practices | 100 |
| 🟢 SEO | 92 |
| 🟢 PWA | 92 |
 
*Lighthouse ran on [https://headless-commerce-poc-pzo3l0tm9-alianza.vercel.app/](https://headless-commerce-poc-pzo3l0tm9-alianza.vercel.app/)*
<!-- Sticky Pull Request Commentlighthouse -->

2021-07-05 10:21 UTC, alianza commented
Testable by logging in with use that has past orders (User: janwillemvanbremen@live.nl WW: JanWillem123) and visiting the homepage. Recommended product will be inserted as first product in the list.

2021-07-06 08:16 UTC, egonm12 requested changes

2021-07-06 08:16 UTC, egonm12 commented on pages/index.tsx
> +      if (result != -1) { products.splice(result, 1) } // If it exists remove it
You are directly mutating state here by calling `splice` and later `unshift` on the state object. This can cause unexpected behavior which google will give you a lot of results why you shouldn't do that. Instead call the `setState` function that is bound to the `product` state or use local state to copy the `products` value and mutate it locally.

2021-07-06 08:16 UTC, egonm12 commented on pages/index.tsx
> +          orderedBrands.push(item.node.variant?.product.vendor) // Collect ordered brands
Same here. You are mutating the state object directly. Create a local variable instead and pass that to `setOrderedBrands`.

Remember that you can always access the previous state of a local state hook, so if you want to add new items to an existing array you can use that and spread it in a new array.

2021-07-06 11:02 UTC, alianza commented on pages/index.tsx
> +      if (result != -1) { products.splice(result, 1) } // If it exists remove it
It seems that setState is unavailable here except if I convert the component to a class component. But then a bunch of other stuff goes wrong. I will try try the local state copy approach instead!

2021-07-06 11:08 UTC, egonm12 commented on pages/index.tsx
> +      if (result != -1) { products.splice(result, 1) } // If it exists remove it
Yeah that might be possible, I am not sure where `products` comes from but in that case local state is fine.

2021-07-06 11:10 UTC, alianza commented on pages/index.tsx
> +      if (result != -1) { products.splice(result, 1) } // If it exists remove it
Yeah `products` comes from the getStaticProps function. I'm now trying to put this in the state with useState and mutating it from there. Will update PR in a bit

2021-07-06 11:42 UTC, egonm12 commented on pages/index.tsx
> +          const productListCopy = productList
You need to spread it in a new array, otherwise the reference to the array is the same.

See: https://www.samanthaming.com/tidbits/35-es6-way-to-clone-an-array/#why-can-t-i-use-to-copy-an-array

2021-07-06 11:42 UTC, egonm12 commented on pages/index.tsx
> +            setOrderedBrands(orderedBrandsCopy) // Set ordered brands
To make this even shorter you can do 
```
setOrderBrands(prevOrderBrands => [...prevOrderBrands, item.node.variant?.product.vendor])
```

2021-07-06 11:44 UTC, alianza commented on pages/index.tsx
> +          const productListCopy = productList
Ahh, of course. Thank you!

2021-07-06 11:47 UTC, egonm12 commented on pages/index.tsx
> +  const [productList, setProductList] = useState<Array<Product>>(products)
Pointing to the type of the original value, which is also your initial state, makes it easier to maintain. If the type of `products` would ever change, this will change as well without manually having to edit it. 

```suggestion
  const [productList, setProductList] = useState<typeof products>(products)
```

2021-07-06 11:49 UTC, egonm12 commented on pages/index.tsx
> +            setOrderedBrands(orderedBrandsCopy) // Set ordered brands
Btw the `?` is not needed, you already check for its existence on line 64

2021-07-06 11:51 UTC, alianza commented on pages/index.tsx
> +  const [productList, setProductList] = useState<Array<Product>>(products)
Nice little trick thanks

2021-07-06 12:27 UTC, alianza commented on pages/index.tsx
> +          orderedBrands.push(item.node.variant?.product.vendor) // Collect ordered brands
Yes I have used this in the current implementation!

2021-07-06 12:51 UTC, egonm12 commented on pages/index.tsx
> +  }, [productList, productListCopy, products, recommendedProducts?.products])
It would be better to move `productListCopy` inside the useEffect so that it will not be a dependency. Also why is `productList` part of the dependency list? This could cause an infinite loop since you are calling `setProductList` in this effect and made `productList` a dependency at the same time and I don't see it being used in this effect.

2021-07-06 13:32 UTC, alianza commented on pages/index.tsx
> +  }, [productList, productListCopy, products, recommendedProducts?.products])
I moved the `productListCopy` inside the useEffect. `productList` is now a dependency because it is used in the useEffect hook to make the `productListCopy`. It should be better like this!

2021-07-08 09:38 UTC, egonm12 commented on pages/index.tsx
> +    }, [customerOrders, productList, products, recommendedProducts?.products])
The dependency `products` is not needed here. You only have a dependency on `productList`.

2021-07-08 11:15 UTC, alianza commented on pages/index.tsx
> +    }, [customerOrders, productList, products, recommendedProducts?.products])
I updated the dependencies list!

2021-07-08 11:19 UTC, egonm12 approved these changes

2021-07-08 11:20 UTC, merged