Categories
kabisa/headless-commerce-poc pull request #27
Opened 2021-07-07 13:56 UTC by alianza

Styling for sorting options on home and search pages.
Updated TailwindCSS to use JIT engine
Updated all nested @screen css queries (For JIT support)
Fixed mobile sorting dropdown label text
Extracted Search component styles to new css module

2021-07-07 15:03 UTC, alianza commented
⚡️ [Lighthouse report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1625670203045-91895.report.html) for the changes in this PR:
| Category | Score |
| --- | --- |
| 🟠 Performance | 54 |
| 🟢 Accessibility | 100 |
| 🟢 Best practices | 100 |
| 🟠 SEO | 88 |
| 🟢 PWA | 92 |
 
*Lighthouse ran on [https://headless-commerce-poc-8ktdrid9f-alianza.vercel.app/](https://headless-commerce-poc-8ktdrid9f-alianza.vercel.app/)*
<!-- Sticky Pull Request Commentlighthouse -->

2021-07-08 09:43 UTC, egonm12 requested changes

2021-07-08 09:43 UTC, egonm12 commented on components/search/Search.tsx
> +  const handleClick = (event: any, filter: string) => {
Why pass the `event` if it is not being used?

2021-07-08 09:43 UTC, egonm12 commented on components/search/Search.tsx
> +                    {categories.map((cat: any) => (
Why did you decide to type this as `any`? TypeScript is smart enough to infer the type here since `categories`' type is `Category[]`. Therefore if you change this to 
```
categories.map(cat => { ... })
```

it will infer the type and know that `cat`'s type is `Category`.

2021-07-08 09:43 UTC, egonm12 commented on components/search/Search.tsx
> +                    {brands.flatMap(({ node }: { node: any }) => (
Why is `brands` type not known?

2021-07-08 09:43 UTC, egonm12 commented on components/search/Search.tsx
> +              {data.products.map((product: Product) => (
Same here, typescript is smart enough to already know that the type of `product` is `Product` :)

2021-07-08 10:55 UTC, alianza commented on components/search/Search.tsx
> +  const handleClick = (event: any, filter: string) => {
I don't know why this is the case. I think because I moved the file to another location it looks like everything in this file has been newly added. The code in Search.tsx is mostly the Next.js Commerce framework. Though I will remove the unused parameter!

2021-07-08 11:00 UTC, alianza commented on components/search/Search.tsx
> +                    {categories.map((cat: any) => (
I did not write this particular piece of code. It originates from the Next.js Commerce framework. Though I have added the type explicitly now (TS wouldn't infer it on it's own for some reason).

2021-07-08 11:09 UTC, alianza commented on components/search/Search.tsx
> +                    {brands.flatMap(({ node }: { node: any }) => (
The Brands type for some reason did not exist in the framework. I added it and fixed the typing issue here!

2021-07-08 11:10 UTC, alianza commented on components/search/Search.tsx
> +              {data.products.map((product: Product) => (
Removed!

2021-07-08 11:18 UTC, egonm12 approved these changes

2021-07-08 11:20 UTC, merged