Fix personalisation
kabisa/headless-commerce-poc pull request #29
Opened 2021-07-09 10:41 UTC by alianza

Fixed personalization issue where products from brands you didn't order from are shown.

2021-07-09 10:45 UTC, alianza commented
⚡️ [Lighthouse report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1625827503375-49728.report.html) for the changes in this PR:
| Category | Score |
| --- | --- |
| 🟠 Performance | 82 |
| 🟢 Accessibility | 100 |
| 🟢 Best practices | 100 |
| 🟢 SEO | 92 |
| 🟢 PWA | 92 |
 
*Lighthouse ran on [https://headless-commerce-poc-pq4kbwadm-alianza.vercel.app/](https://headless-commerce-poc-pq4kbwadm-alianza.vercel.app/)*
<!-- Sticky Pull Request Commentlighthouse -->

2021-07-14 14:10 UTC, pascalw commented on pages/index.tsx
> +    brandId: _.sample(orderedBrands) || '***---***', // If no ordered brands search for placeholder string (No results)
Hmm this is quite an ugly hack to be honest 😅 Can we instead make sure that no search query is performed, if there aren't any ordered brands?

2021-07-14 14:10 UTC, pascalw commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts?.products])
Can you extract all of this into a separate module? These kinds of details don't belong in a page. A Page should be able to call a single function `getRecommendedProducts(userId)` and not have to know any of the details _how_ it's done.

This is a general design pattern that I think is crucial to keep a clean codebase; separate the _what_ (`getRecommendProducts`) and the how (using the most recently ordered brands in this case). This has a few benefits:

1. If I'm trying to understand what happens when the homepage is rendered, I don't want to have to sift through all sorts of implementation details. I just want to see quickly that it fetches some products from a category and recommend products. If I want to know the details, I can drill down into the specific functions that implement this.
2. If you in the future change _how_ we determine recommended products, you can just update the `getRecommendProducts` function and the rest of the system doesn't know or care.

2021-07-14 14:18 UTC, alianza commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts?.products])
I totally agree and will extract this functionality.

2021-07-14 14:19 UTC, alianza commented on pages/index.tsx
> +    brandId: _.sample(orderedBrands) || '***---***', // If no ordered brands search for placeholder string (No results)
Haha, I agree. Though you can't use the useSearch hook in a conditional so it is executed as the page is loaded an everytime it updates. I will look into a cleaner way to take care of this though I have not found it yet..

2021-07-14 15:31 UTC, alianza commented on pages/index.tsx
> +    brandId: _.sample(orderedBrands) || '***---***', // If no ordered brands search for placeholder string (No results)
I wasn't able to use the hook in a conditional. So I have also extracted the getting of the BrandId to the recommendations module to abstract the hack away. Let me know what you think or if you have any tips on calling that useSearch method conditionally.

2021-07-15 12:27 UTC, pascalw requested changes

2021-07-15 12:27 UTC, pascalw commented on pages/index.tsx
> +  }, [customerOrders?.orders.edges, orderedBrands])
This still leaves quite a lot of logic about _how_ recommended products are determined, here in the view layer. Is it possible to completely abstract this in a function? `const recommendedProducts = useRecommendedProducts()` or something like that.

2021-07-15 12:27 UTC, pascalw commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts])
This is pretty difficult to understand IMO. I think it would be much clearer if the recommended product(s) are explicitly passed to the `HomeAllProductsGrid`. Now the `getRecommendedProduct` hook is modifying the list of products, this is very unexpected.

I'm giving you a bit of a hard time about this since it's really important you learn how to separate concerns. It's IMO a huge quality if code does what you think it does. I wouldn't expect a function that is prefixed with `get` to modify some state. A function prefixed with `get` should GET something, not silently modify state. But also in general, the code would be much easier to follow if you'd have a list of products and a list of recommended products.

2021-07-15 14:04 UTC, alianza commented on pages/index.tsx
> +  }, [customerOrders?.orders.edges, orderedBrands])
I have abstracted the getting of the recommended product in a custom hook. Adding the recommended product to the other products I have also created a custom function for.

2021-07-15 14:08 UTC, alianza commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts])
I have now created the `useRecommendedProduct` hook to get the recommended product. Another function called `addRecommendedProduct` takes `products` and `recommendedProduct` as parameters and adds the `recommendedProduct` to the `products`by modifying it, this is necessary because if the `recommendedProduct` already exists in `products` it needs to be removed and added at the beginning of the list. I think this is a better implementation than before, let me know what you think.

2021-07-16 08:03 UTC, pascalw commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts])
This is already a bit better but not quite there yet :-)

The goal is to remove domain logic from your React components. React components should be focused on rendering UI, not on business logic. What I would like to see in the React component is something like this:

```js
const productsWithRecommendations = useProductsWithRecommendations(products);

// render products
```

That's the only thing the UI layer has to know. There's a set of fixed products that are the same for every user and we want to add recommended products that are user specific to it. As the UI layer we don't want to know _how_ that's done, we just want to get a list of products that includes recommendations. It's all about responsibilities. It's the responsibility of the UI layer to _know_ it should retrieve recommended products, but it shouldn't have to know _how_ to that's done under the hood.

I've created a small example to demonstrate what I mean: https://codepen.io/pascalw/pen/qBmreGY. It takes a fixed list of products (represented as a list of integers, for brevity) and dynamically adds a 'product' to it after 3 seconds, to simulate this is retrieved from the network. Let me know what you think!

2021-07-16 09:28 UTC, alianza commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts])
This looks very good. I'm now trying to implement something similar in the project. I will update the PR once I have it working! Thanks for the example :)

2021-07-16 10:47 UTC, alianza commented on pages/index.tsx
> +  }, [customerOrders, productList, recommendedProducts])
@pascalw I have updated the implementation and PR according to your suggestions. I think It's better like this!

2021-07-16 12:19 UTC, pascalw reviewed
Nice progress, almost there!

2021-07-16 12:19 UTC, pascalw commented on components/common/HomeAllProductsGrid/HomeAllProductsGrid.tsx
> +  const productsWithRecommendation = useProductsWithRecommendation(products ,locale);
Components should be as dumb as possible, focusing on data presentation. This kind of logic really belongs on the container component level, the page in this case.

2021-07-16 12:19 UTC, pascalw commented on pages/index.tsx
> +import type {GetStaticPropsContext, InferGetStaticPropsType} from 'next'
This import can be removed?

2021-07-16 12:19 UTC, pascalw commented on lib/recommendations.ts
> +export function useProductsWithRecommendation(products: Product[], locale: string | undefined): Product[] {
This can be simplified quite a bit still.

There's only one piece of state needed really, and that's the list of products including the list of recommend products.

2021-07-16 12:19 UTC, pascalw commented on lib/recommendations.ts
> +  useEffect(() => {
It seems `useEffect` is not needed here? Components that use this hook will re-render when you update the state.

2021-07-16 12:19 UTC, pascalw commented on lib/recommendations.ts
> +  useEffect(() => {
Same here, no useEffect hook needed.

2021-07-16 12:19 UTC, pascalw commented on lib/recommendations.ts
> +  })
Let's break this up into a few functions. It really helps to think of your code like prose. If I want to know how recommended products work, I just need to know the following:

1. We retrieve the last 3 orders
2. We determine which brand is ordered most often
3. We fetch products from that brand

Now, translating this into code, the code could look something like this:

```js
const customerOrders = fetchCustomerOrders({ numberOfOrders: 3});
const mostOrderedBrand = determineMostOrderedBrand(customerOrders);
const recommendProducts = fetchProducts({brand: mostOrderedBrand});

setRecommendProducts(products.concat(recommendedProducts));
```

That way the code is easy to grasp. It reads like prose. If I want or need to know how exactly we determine which brand is ordered most often, I can look at the `determineMostOrderedBrand`. But I don't _have_ to go through all that code to understand the overflow flow.

Does that make sense?

2021-07-16 12:54 UTC, alianza commented on components/common/HomeAllProductsGrid/HomeAllProductsGrid.tsx
> +  const productsWithRecommendation = useProductsWithRecommendation(products ,locale);
Okay, will move the `useProductsWithRecommendation` function call back to the page.

2021-07-16 12:56 UTC, alianza commented on pages/index.tsx
> +import type {GetStaticPropsContext, InferGetStaticPropsType} from 'next'
Doesn't seem like it...

2021-07-16 13:03 UTC, alianza commented on lib/recommendations.ts
> +  })
This makes total sense! Will try to get as close as possible to this type of implementation!

2021-07-16 13:50 UTC, alianza commented on lib/recommendations.ts
> +  })
I think the implementation I have now is pretty good! Thanks so much for the tips, it really helped me get to the current implementation which I'm much happier with.

2021-07-16 14:15 UTC, pascalw approved these changes
👌

2021-07-16 14:17 UTC, merged

2021-07-16 14:21 UTC, pascalw commented on lib/productRecommendations.ts
> +    customerOrders?.map((order: OrderEdge) => { // Iterate through orders
FYI you're using [Array.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) here, but you're using it as if it was [Array.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).

I generally prefer `map` over `forEach`, but in this case you're not mapping one-on-one (due to the vendor potentially being unknown), so then forEach is more appropriate.

2021-07-16 14:21 UTC, pascalw commented on lib/productRecommendations.ts
> +            if (vendor && orderedBrands.indexOf(vendor) === -1) { // If vendor is known and doesn't exist in orderedBrands list yet
You could also use a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) instead of an Array, if you want items to be unique.